#!/usr/bin/env python3
"""Regenerate every Since Toggle logo derivative from the sincelabs brand kit.

Canonical source is the sincelabs/brand tile (terracotta rounded square with
the warm-white // mark). Requires Pillow; cairosvg only when the tile PNG
cache is missing.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parent.parent
BRAND = Path(os.environ.get(
    "SINCE_BRAND_KIT",
    "/home/openhands/workspaces/brand/assets/logo",
))
TILE_CACHE = ROOT / "assets" / "since-tile-terracotta-1024.png"
MARK = BRAND / "png" / "since-mark-1024.png"
ASSETS = ROOT / "assets"
WEB = ROOT / "web"

# Static branded graphics that embed the logo directly. Their surrounding
# layout stays untouched; only the existing logo tile is replaced.
COMPOSITE_LOGOS = (
    (ASSETS / "banners" / "sincetoggle-banner-en.png", (140, 228, 396, 484), 48),
    (ASSETS / "banners" / "sincetoggle-banner-tr.png", (140, 228, 396, 484), 48),
    (ASSETS / "banners" / "sincetoggle-banner-vertical-en.png", (472, 456, 808, 792), 64),
    (ASSETS / "sincetoggle-social-card-300x188.png", (91, 25, 126, 60), 8),
    (ASSETS / "sincetoggle-social-card.png", (436, 84, 556, 204), 26),
    (WEB / "assets" / "sincetoggle-ollama-heart.png", (202, 175, 460, 433), 30),
)


def load_tile() -> Image.Image:
    if TILE_CACHE.exists():
        return Image.open(TILE_CACHE).convert("RGBA")
    import cairosvg
    TILE_CACHE.parent.mkdir(parents=True, exist_ok=True)
    cairosvg.svg2png(
        url=str(BRAND / "since-tile-terracotta.svg"),
        write_to=str(TILE_CACHE),
        output_width=1024,
        output_height=1024,
    )
    return Image.open(TILE_CACHE).convert("RGBA")


TILE = load_tile()
MARK_IMG = Image.open(MARK).convert("RGBA")


def full_logo(size: int) -> Image.Image:
    return TILE.resize((size, size), Image.Resampling.LANCZOS)


def icon_logo(size: int) -> Image.Image:
    """The // mark centered on the terracotta tile with even padding."""
    canvas = full_logo(size).copy()
    mark = MARK_IMG.copy()
    mark.thumbnail((int(size * 0.62), int(size * 0.62)), Image.Resampling.LANCZOS)
    canvas.alpha_composite(mark, ((size - mark.width) // 2, (size - mark.height) // 2))
    return canvas


def save_png(image: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, format="PNG", optimize=True)


def save_jpeg(image: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.convert("RGB").save(
        path,
        format="JPEG",
        quality=94,
        optimize=True,
        progressive=True,
    )


def replace_composite_logo(path: Path, box: tuple[int, int, int, int], radius: int) -> None:
    image = Image.open(path).convert("RGB")
    left, top, right, bottom = box
    width, height = right - left, bottom - top
    if width != height:
        raise SystemExit(f"Composite logo box must be square: {path} {box}")

    tile = full_logo(width).convert("RGB")
    mask = Image.new("L", (width, height), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, width - 1, height - 1), radius=radius, fill=255)
    image.paste(tile, (left, top), mask)
    save_png(image, path)


def main() -> None:
    save_png(full_logo(1024), ASSETS / "logo-github.png")
    save_jpeg(full_logo(128), ASSETS / "logo-github-128.jpg")
    save_png(full_logo(512), ASSETS / "logo-github-512.png")
    save_jpeg(full_logo(512), ASSETS / "logo-github-512.jpg")

    for size in (64, 128):
        save_png(icon_logo(size), ASSETS / f"store-icon-{size}.png")

    for browser in ("chrome", "firefox"):
        icon_dir = ROOT / "src" / browser / "icons"
        for size in (16, 48, 128):
            save_png(icon_logo(size), icon_dir / f"icon{size}.png")

    shutil.copyfile(ASSETS / "logo-github.png", WEB / "logo-github.png")
    save_png(icon_logo(64), WEB / "favicon.png")
    # Website social cards are typography-led composites generated by
    # assets/brand-assets-2026-2/render.mjs. Do not replace them with
    # logo-only derivatives here.

    for path, box, radius in COMPOSITE_LOGOS:
        replace_composite_logo(path, box, radius)

    print("Synchronized Since Toggle logo assets from the sincelabs brand kit")


if __name__ == "__main__":
    main()
